categories:
  nasdaq_tech:
  - NVDA
  - MSFT
  - AAPL
  - AMD
  - INTC
  - ASML
  - MU
  - AMAT
  - KLAC
  - LRCX
  - MRVL
  - PANW
  - CRWD
  - FTNT
  - ZS
  - NET
  - SNPS
  - CDNS
  - MCHP
  - NXPI
  - 'ON'
  - MPWR
  - ARM
  - WDAY
  - ADBE
  - CRM
  - ORCL
  - NOW
  - INTU
  - QCOM
  growth:
  - SHOP
  - SQ
  - PYPL
  - ABNB
  - UBER
  - DDOG
  - SNOW
  - PLTR
  - COIN
  - RBLX
  - HOOD
  - SOFI
  - AFRM
  - RIVN
  - NIO
  - SMCI
  - APP
  - DUOL
  - ROKU
  - PINS
  - SNAP
  - SPOT
  - TTD
  - HUBS
  - DASH
  - SE
  - UPST
  - IONQ
tickers:
- NVDA
- MSFT
- AAPL
- AMD
- INTC
- ASML
- MU
- AMAT
- KLAC
- LRCX
- MRVL
- PANW
- CRWD
- FTNT
- ZS
- NET
- SNPS
- CDNS
- MCHP
- NXPI
- 'ON'
- MPWR
- ARM
- WDAY
- ADBE
- CRM
- ORCL
- NOW
- INTU
- QCOM
- SHOP
- SQ
- PYPL
- ABNB
- UBER
- DDOG
- SNOW
- PLTR
- COIN
- RBLX
- HOOD
- SOFI
- AFRM
- RIVN
- NIO
- SMCI
- APP
- DUOL
- ROKU
- PINS
- SNAP
- SPOT
- TTD
- HUBS
- DASH
- SE
- UPST
- IONQ
- AGNC
- AXT
- AAR
- BP
- RXO
- HP
